[package]
name = "qr-frontend"
version = "0.1.0"
edition = "2021"
authors = ["Den1zzDev"]
license = "MIT"
repository = "https://github.com/Den1zzDev/qr.den1zz.dev"
homepage = "https://qr.den1zz.dev"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "prerender"
path = "src/bin/prerender.rs"
required-features = ["ssr"]

[features]
default = []
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr"]

[dependencies]
qr-core = { path = "../qr-core", default-features = false }
leptos = { version = "0.7" }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlInputElement",
    "HtmlCanvasElement",
    "HtmlImageElement",
    "CanvasRenderingContext2d",
    "FileReader",
    "ProgressEvent",
    "Clipboard",
    "Navigator",
    "Window",
    "Document",
    "Element",
    "File",
    "FileList",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "HtmlAnchorElement",
] }
console_error_panic_hook = "0.1"
